/**
 * Shared test helpers.
 *
 * Helpers insert only what a test explicitly needs rather than seeding the full demo
 * dataset, which keeps each test readable and keeps dependencies explicit.
 */
import { eq } from "drizzle-orm";
import {
  artists,
  artistConsents,
  drops,
  dropProducts,
  events,
  eventVerificationTokens,
  fanPreferences,
  inventory,
  products,
  productVariants,
  shippingOptions,
  tours,
  userRoles,
  users,
  venues,
  verifiedAttendance,
} from "@/db/schema";
import type { AuthContext } from "@/server/auth/session";
import type { DropStatus, PlatformRole } from "@/lib/types";

export function db() {
  return globalThis.__testDb;
}

let seq = 0;
function uid(prefix: string) {
  return `${prefix}_test_${++seq}_${Math.random().toString(36).slice(2, 8)}`;
}

export async function createUser(overrides: {
  displayName?: string;
  email?: string;
  passwordHash?: string;
} = {}) {
  // `users.id` is a uuid generated by the database, so only the email needs a tag to
  // stay unique across a suite.
  const tag = uid("usr");
  const [user] = await db()
    .insert(users)
    .values({
      displayName: overrides.displayName ?? "Test Fan",
      email: overrides.email ?? `${tag}@example.com`,
      passwordHash: overrides.passwordHash ?? "hash",
    })
    .returning();
  return user;
}

export async function grantRole(userId: string, role: PlatformRole) {
  await db().insert(userRoles).values({ userId, role });
}

export async function createArtist(name = "Test Artist") {
  const id = uid("art");
  const [artist] = await db()
    .insert(artists)
    .values({ id, slug: id, name })
    .returning();
  return artist;
}

export async function createVenue() {
  const id = uid("ven");
  const [venue] = await db()
    .insert(venues)
    .values({
      id,
      name: "Test Venue",
      city: "Detroit",
      country: "US",
      lat: 42.33,
      lng: -83.05,
      timezone: "America/Detroit",
      geofenceRadiusMeters: 400,
    })
    .returning();
  return venue;
}

export async function createTour(artistId: string) {
  const id = uid("tor");
  const [tour] = await db()
    .insert(tours)
    .values({ id, artistId, slug: id, name: "Test Tour", postShowWindowMinutes: 480 })
    .returning();
  return tour;
}

export async function createEvent(
  artistId: string,
  tourId: string,
  venueId: string,
  overrides: {
    startsAt?: Date;
    endsAt?: Date;
    cancelled?: boolean;
    postShowWindowMinutes?: number | null;
  } = {},
) {
  const now = new Date();
  const id = uid("evt");
  const [event] = await db()
    .insert(events)
    .values({
      id,
      artistId,
      tourId,
      venueId,
      slug: id,
      startsAt: overrides.startsAt ?? now,
      endsAt: overrides.endsAt ?? new Date(now.getTime() + 2 * 60 * 60_000),
      timezone: "America/Detroit",
      cancelled: overrides.cancelled ?? false,
      postShowWindowMinutes: overrides.postShowWindowMinutes ?? null,
    })
    .returning();
  return event;
}

export async function createEventToken(eventId: string, token = uid("tok")) {
  const [row] = await db()
    .insert(eventVerificationTokens)
    .values({ eventId, token, active: true })
    .returning();
  return row;
}

export async function createVerifiedAttendance(userId: string, eventId: string, tokenId?: string) {
  const [row] = await db()
    .insert(verifiedAttendance)
    .values({ userId, eventId, method: "event_qr", tokenId: tokenId ?? null })
    .returning();
  return row;
}

export async function createProduct(
  artistId: string,
  overrides: {
    accessType?: string;
    eventId?: string;
    tourId?: string;
    name?: string;
    basePriceCents?: number;
    unitCostCents?: number;
    images?: string[];
    active?: boolean;
  } = {},
) {
  const id = uid("prd");
  const [product] = await db()
    .insert(products)
    .values({
      id,
      artistId,
      slug: id,
      name: overrides.name ?? "Test Product",
      category: "apparel",
      accessType: (overrides.accessType as import("@/lib/types").ProductAccessType) ?? "public",
      basePriceCents: overrides.basePriceCents ?? 4500,
      unitCostCents: overrides.unitCostCents ?? null,
      images: overrides.images ?? null,
      active: overrides.active ?? true,
      sku: id,
      eventId: overrides.eventId ?? null,
      tourId: overrides.tourId ?? null,
    })
    .returning();
  return product;
}

export async function createVariantWithInventory(
  productId: string,
  onHand = 10,
  overrides: { size?: string | null; priceDeltaCents?: number } = {},
) {
  const id = uid("var");
  const [variant] = await db()
    .insert(productVariants)
    .values({
      id,
      productId,
      sku: id,
      size: overrides.size === undefined ? "M" : overrides.size,
      priceDeltaCents: overrides.priceDeltaCents ?? 0,
    })
    .returning();
  await db().insert(inventory).values({ variantId: id, onHand, reserved: 0, reorderPoint: 2 });
  return variant;
}

export async function createDrop(
  artistId: string,
  overrides: {
    eventId?: string;
    status?: DropStatus;
    startsAt?: Date;
    endsAt?: Date | null;
  } = {},
) {
  const id = uid("drp");
  const now = new Date();
  const [drop] = await db()
    .insert(drops)
    .values({
      id,
      artistId,
      slug: id,
      title: "Test Drop",
      eventId: overrides.eventId ?? null,
      status: overrides.status ?? "live",
      startsAt: overrides.startsAt ?? new Date(now.getTime() - 60_000),
      endsAt: overrides.endsAt === undefined ? new Date(now.getTime() + 60 * 60_000) : overrides.endsAt,
    })
    .returning();
  return drop;
}

export async function addDropProduct(dropId: string, productId: string, dropPriceCents?: number) {
  const [row] = await db()
    .insert(dropProducts)
    .values({ dropId, productId, dropPriceCents: dropPriceCents ?? null })
    .returning();
  return row;
}

export async function createShippingOption(
  artistId: string,
  overrides: Partial<typeof shippingOptions.$inferInsert> = {},
) {
  const id = uid("shp");
  const [option] = await db()
    .insert(shippingOptions)
    .values({
      id,
      artistId,
      name: "Standard",
      speed: "standard",
      carrierCostCents: overrides.carrierCostCents ?? 700,
      baseCustomerChargeCents: overrides.baseCustomerChargeCents ?? 500,
      strategy: overrides.strategy ?? "fan_pays_full",
      subsidyCents: overrides.subsidyCents ?? 0,
      freeThresholdCents: overrides.freeThresholdCents ?? null,
      eventId: overrides.eventId ?? null,
      tourId: overrides.tourId ?? null,
      deliveryMinDays: overrides.deliveryMinDays ?? 3,
      deliveryMaxDays: overrides.deliveryMaxDays ?? 7,
      ...overrides,
    })
    .returning();
  return option;
}

/**
 * An AuthContext for a signed-in user, mirroring what `getAuthContext` builds. Server
 * Actions read the session through that function, so tests stub it with one of these.
 */
export function authContextFor(
  user: { id: string; email: string; displayName: string },
  overrides: {
    roles?: PlatformRole[];
    memberships?: AuthContext["memberships"];
    activeArtistId?: string | null;
  } = {},
): AuthContext {
  return {
    sessionId: uid("ses"),
    userId: user.id,
    email: user.email,
    displayName: user.displayName,
    roles: overrides.roles ?? ["fan"],
    memberships: overrides.memberships ?? [],
    activeArtistId: overrides.activeArtistId ?? null,
    onboardingCompletedAt: new Date(),
  };
}

export function membershipFor(
  artist: { id: string; name: string; slug: string },
  canPublish = true,
): AuthContext["memberships"][number] {
  return {
    artistId: artist.id,
    artistName: artist.name,
    artistSlug: artist.slug,
    role: "management",
    canPublish,
  };
}

export async function createConsent(userId: string, artistId: string, type: "drops" | "anniversary" | "show_news" | "attendee_offers" = "drops") {
  const [row] = await db()
    .insert(artistConsents)
    .values({ userId, artistId, consentType: type, status: "granted" as const, source: "post_verification_prompt" as const, grantedAt: new Date() })
    .returning();
  return row;
}

export async function setFanShippingAddress(
  userId: string,
  address: {
    shippingName?: string;
    shippingLine1?: string;
    shippingLine2?: string;
    shippingCity?: string;
    shippingRegion?: string;
    shippingPostalCode?: string;
    shippingCountry?: string;
  },
) {
  await db()
    .insert(fanPreferences)
    .values({ userId, ...address })
    .onConflictDoUpdate({
      target: fanPreferences.userId,
      set: address,
    });
}

export async function getFanShippingAddress(userId: string) {
  const [row] = await db()
    .select({
      shippingName: fanPreferences.shippingName,
      shippingLine1: fanPreferences.shippingLine1,
      shippingLine2: fanPreferences.shippingLine2,
      shippingCity: fanPreferences.shippingCity,
      shippingRegion: fanPreferences.shippingRegion,
      shippingPostalCode: fanPreferences.shippingPostalCode,
      shippingCountry: fanPreferences.shippingCountry,
    })
    .from(fanPreferences)
    .where(eq(fanPreferences.userId, userId))
    .limit(1);
  return row ?? null;
}

export async function setFanApparelSize(userId: string, apparelSize: string) {
  await db()
    .insert(fanPreferences)
    .values({ userId, apparelSize })
    .onConflictDoUpdate({
      target: fanPreferences.userId,
      set: { apparelSize },
    });
}

export async function getFanApparelSize(userId: string) {
  const [row] = await db()
    .select({ apparelSize: fanPreferences.apparelSize })
    .from(fanPreferences)
    .where(eq(fanPreferences.userId, userId))
    .limit(1);
  return row?.apparelSize ?? null;
}
